services:
  - type: web
    name: expense-tracker
    runtime: python
    plan: free
    rootDir: expense-tracker
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --threads 4
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: SHARE_WITH_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
